# Generated by Django 5.0.6 on 2024-09-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_favoritepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
    ]
