# Generated by Django 5.0.6 on 2024-09-02 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_alter_comment_options_comment_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
