# Generated by Django 5.0.6 on 2024-09-02 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 7, 45, 4, 158115, tzinfo=datetime.timezone.utc)),
        ),
    ]
