# Generated by Django 5.0.6 on 2024-08-13 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
