# Generated by Django 5.0.6 on 2024-09-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_podcastcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='podcastcomment',
            options={'ordering': ['-created_date']},
        ),
    ]
